name: Deploy

on:
  push:
    branches:
      - main
env:
  REGISTRY: docker.io
  NODE_IMAGE: gokarni/client-a-node-app
  PYTHON_IMAGE: gokarni/client-b-python-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 2️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build Client-A
      - name: Build Client-A
        run: |
          docker build -t $NODE_IMAGE:${IMAGE_TAG} ./devops-sample-nest

      # 4️⃣ Build Client-B
      - name: Build Client-B
        run: |
          docker build -t $PYTHON_IMAGE:${IMAGE_TAG} ./devops-sample-fast

      # 5️⃣ Push Images
      - name: Push Images
        run: |
          docker push  $NODE_IMAGE:${IMAGE_TAG}
          docker push $PYTHON_IMAGE:${IMAGE_TAG}

      # 6️⃣ Deploy Stack via SSH
      # upddated the code
      - name: Deploy Stack
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf DevOps-Assignment-Task

            git clone https://github.com/Gokarni/DevOps-Assignment-Task.git

            cd DevOps-Assignment-Task
            IMAGE_TAG=${{ github.sha }}
            IMAGE_TAG=${IMAGE_TAG::7}

            echo "Using IMAGE_TAG=$IMAGE_TAG"

            export IMAGE_TAG
                    
            docker stack deploy --with-registry-auth -c stack.yml multi 

            docker stack services multi
