name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build Client-A
      - name: Build Client-A
        run: |
          docker build -t gokarni/client-a-node-app:${{ github.sha }} ./devops-sample-nest

      # 4️⃣ Build Client-B
      - name: Build Client-B
        run: |
          docker build -t gokarni/client-b-python-app:${{ github.sha }} ./devops-sample-fast

      # 5️⃣ Push Images
      - name: Push Images
        run: |
          docker push gokarni/client-a-node-app:${{ github.sha }}
          docker push gokarni/client-b-python-app:${{ github.sha }}

      # 6️⃣ Deploy Stack via SSH
      - name: Deploy Stack
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/DevOps-Assignment-Task
            sed -i "s/\${IMAGE_TAG}/${GITHUB_SHA}/g" stack.yml
            
            
            docker stack deploy \
              -c stack.yml \
              multi \
              --with-registry-auth

            docker stack services multi
